# Generated by Django 5.0.7 on 2024-07-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_product_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=50)),
                ('range', models.CharField(max_length=50, null=True)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cart',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='cartitem',
            new_name='price',
        ),
    ]
