# Generated by Django 5.0.7 on 2024-07-19 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart_cartitem_rename_cart_product_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='category',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.customer'),
        ),
    ]
