# Generated by Django 5.0.7 on 2024-07-19 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_category_cart_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='brand',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='detail',
            new_name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='range',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
