# Generated by Django 5.0.7 on 2024-07-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_brand_cartitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
