# Generated by Django 5.0.7 on 2024-07-22 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_productqueryset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductQuerySet',
        ),
    ]
