# Generated by Django 5.0.7 on 2024-07-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_user_delete_createcustomer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='product',
            name='isactive',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='isdeleted',
            field=models.BooleanField(blank=True, max_length=10, null=True),
        ),
    ]
