# Generated by Django 5.0.7 on 2024-07-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_user_product_isactive_product_isdeleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
