# Generated by Django 5.0.7 on 2024-07-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_isactive_alter_product_isdeleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='isactive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='isdeleted',
            new_name='is_deleted',
        ),
    ]
